
export const mapResults = {
    '[Samutsongkhram]_Amphawa Floating Market': 'ตลาดน้ำอัมพวา, สมุทรสงคราม',
    '[Ratchaburi]_Hin Khao Ngu National Park': 'อุทยานหินเขางู, ราชบุรี',
    '[Ratchaburi]_Damnoen Saduak Floating Market': 'ตลาดน้ำดำเนินสะดวก, ราชบุรี',
    '[Suphanburi]_Sam Chuk Market': 'ตลาดสามชุก, สุพรรณบุรี',
    '[Lopburi]_Pasak Chonlasit Dam': 'เขื่อนป่าสักชลสิทธิ์, ลพบุรี',
    '[Singburi]_Wat Phra Non Chak Si Worawihan': 'วัดพระนอนจักรสีห์วรวิหาร, สิงห์บุรี',
    '[Suphanburi]_Phu Toei National Park': 'อุทยานแห่งชาติพุเตย, สุพรรณบุรี',
    '[Suphanburi]_Giant Fishing Trap': 'สุ่มปลาขนาดใหญ่ยักษ์, สุพรรณบุรี',
    '[Lopburi]_Pra Prang Sam Yod': 'พระปรางค์สามยอด, ลพบุรี',
    '[Angthong]_Wat Muang': 'วัดม่วง, อ่างทอง',
    '[Angthong]_Wat Phrathat Chedi Sri Pho Thong': 'วัดพระธาตุเจดีย์ศรีโพธิ์ทอง, อ่างทอง',
    '[Ratchaburi]_Moo Ban Huai Nam Sai': 'หมู่บ้านห้วยน้ำใส, ราชบุรี',
    '[Satun]_Ko Lipe': 'เกาะหลีเป๊ะ, สตูล',
    '[Trang]_Morakot Cave': 'ถ้ำมรกต, ตรัง',
    '[Nakhonsithammarat]_Khiri Wong Village': 'หมู่บ้านคีรีวง, นครศรีธรรมราช',
    '[Chumphon]_Mu Ko Chumphon National Park': 'อุทยานแห่งชาติหมู่เกาะชุมพร, ชุมพร',
    '[Nakhonsithammarat]_Wat Mahathat Worawihan': 'วัดพระมหาธาตุวรมหาวิหาร, นครศรีธรรมราช',
    '[Phatthalung]_Thale Noi': 'ทะเลน้อย, พัทลุง',
    '[Yala]_Talay Mok Aiyoeweng': 'ทะเลหมอกอัยเยอร์เวง, ยะลา',
    '[Pattani]_Bang Pu': 'บางปู, ปัตตานี',
    '[Nakhonsithammarat]_Khanom': 'ขนอม, นครศรีธรรมราช',
    '[Phatthalung]_Khao Ok Talu': 'เขาอกทะลุ พัทลุง',
    '[Yala]_Betong Winter Flower': 'สวนไม้ดอกเมืองหนาวเบตง, เบตง',
    '[Narathiwat]_Ao Manao National Park': 'อุทยานอ่าวมะนาว, นราธิวาส',
    '[Ranong]_Laem Son National Park': 'อุทยานแห่งชาติแหลมสน, ระนอง',
    '[Pattani]_Namtok Sai Khao National Park': 'อุทยานแห่งชาติน้ำตกทรายขาว, ปัตตานีและยะลา',
    '[Buriram]_Phanom Rung Historical Park': 'อุทยานประวัติศาสตร์พนมรุ้ง, บุรีรัมย์',
    '[Loei]_Phu Kradueng National Park': 'อุทยานภูกระดึง, เลย',
    '[Ubonratchathani]_Pha Tam National Park': 'อุทยานผาแต้ม, อุบลราชธานี',
    '[Nakhonphanom]_Wat Prathat Phanom': 'วัดพระธาตุพนมวรมหาวิหาร, นครพนม',
    '[Loei]_Chiang Khan': 'เชียงคาน, เลย',
    '[Ubonratchathani]_Sam Phan Bok': 'สามพันโบก, อุบลราชธานี',
    '[Mukdahan]_Ho Kaeo Mukdahan': 'หอแก้วมุกดาหารเฉลิมพระเกียรติ, มุกดาหาร',
    '[Srisaket]_Wat Pa Maha Chedi Kaew': 'วัดป่ามหาเจดีย์แก้ว, ศรีสะเกษ',
    '[Roiet]_Wat Pha Nam Yoi': 'วัดผาน้ำย้อย, ร้อยเอ็ด',
    '[Buengkan]_Phu Tok': 'ภูทอก, บึงกาฬ',
    '[Udonthani]_Kham Chanod': 'คําชะโนด, อุดรธานี',
    '[Sakonnakhon]_Nong Han': 'หนองหาร, สกลนคร',
    '[Buriram]_Prasat Muang Tam': 'ปราสาทเมืองต่ำ, บุรีรัมย์',
    '[Mahasarakham]_Phrathat Na Dun': 'พระธาตุนาดูน, มหาสารคาม',
    '[Nongbualamphu]_150 million year old stone shellfish Museum': 'พิพิธภัณฑ์หอยหิน 150 ล้านปีและไดโนเสาร์โนนทัน, หนองบัวลำภู',
    '[Nongkhai]_Sala Keoku': 'ศาลาแก้วกู่, หนองคาย',
    '[Buengkan]_Hin Sam Wan': 'หินสามวาฬ, บึงกาฬ',
    '[Nakhonphanom]_Phu Langka National Park': 'อุทยานแห่งชาติภูลังกา, นครพนม',
    '[Phetchabun]_Phu Thap Buek': 'ภูทับเบิก, เพชรบูรณ์',
    '[Chiangrai]_Wat Prathat Doi Tung': 'วัดพระมหาชินธาตุเจ้า(ดอยตุง), เชียงราย',
    '[Nan]_Wat Phumin': 'วัดภูมินทร์, น่าน',
    '[Chiangrai]_Phu Chi Fa': 'วนอุทยานภูชี้ฟ้า, เชียงราย',
    '[Nan]_Doi Samer Dao': 'ดอยเสมอดาว, น่าน',
    '[Sukhothai]_Sukhothai Historical Park': 'อุทยานประวัติศาสตร์สุโขทัย, สุโขทัย',
    '[Maehongson]_Pang Oung': 'ปางอุ๋ง, แม่ฮ่องสอน',
    '[Phetchabun]_Wat Phrathat Pha Sorn Kaew': 'วัดพระธาตุผาซ่อนแก้ว, เพชรบูรณ์',
    '[Phitsanulok]_Phi Hin Rong Kla National Park': 'อุทยานแห่งชาติภูหินร่องกล้า, พิษณุโลกและเพชรบูรณ์',
    '[Lamphun]_Wat Phrathat Haripunchai': 'วัดพระธาตุหริภุญชัยวรมหาวิหาร, ลําพูน',
    '[Phitsanulok]_Wat Pra Si Rattana Mahathat Woramahawihan': 'วัดพระศรีรัตนมหาธาตุวรมหาวิหาร, พิษณุโลก',
    '[Maehongson]_Pai': 'บ้านสันติชลปาย, แม่ฮ่องสอน',
    '[Lampang]_Mae Moh Power Plant': 'โรงไฟฟ้าแม่เมาะ, ลําปาง',
    '[Tak]_Thi Lo Su Waterfall': 'น้ำตกทีลอซู, ตาก',
    '[Phrae]_Wat Phrathat Chao Hae': 'วัดพระธาตุช่อแฮพระอารามหลวง, แพร่',
    '[Lampang]_Chae Son National Park': 'อุทยานแห่งชาติแจ้ซ้อน, ลำปาง',
    '[Nan]_Bo Kluea': 'บ่อเกลือ, น่าน',
    '[Phayao]_Phayao Lake': 'กว๊านพะเยา, พะเยา',
    '[Nakhonsawan]_Nakhon Sawan Observation Town': 'หอชมเมืองนครสวรรค์, นครสวรรค์',
    '[Uthaithani]_Sakae Krang': 'ชุมชนชาวแพสะแกกรัง, อุทัยธานี',
    '[Tak]_Umphang Wildlife Sanctuary': 'เขตรักษาพันธุ์สัตว์ป่าอุ้มผาง, ตาก',
    '[Maehongson]_Meahongson City': 'ตัวเมืองแม่ฮ่องสอน, แม่ฮ่องสอน',
    '[Uttaradit]_Phu Soi Dao National Park': 'ภูสอยดาว, พิษณุโลกและอุตรดิตถ์',
    '[Phichit]_Bueng Si Fai': 'บึงสีไฟ, พิจิตร',
    '[Phetchabun]_Windmill Khao Kho': 'ทุ่งกังหันลมเขาค้อ, เพชรบูรณ์',
    '[Kamphaengphet]_Kampangphet Historical Park': 'อุทยานประวัติศาสตร์กําแพงเพชร, กําแพงเพชร',
    '[Trat]_Ko Chang': 'เกาะช้าง, ตราด',
    '[Chanthaburi]_Kung Krabaen Beach': 'อ่าวคุ้งกระเบน, จันทบุรี',
    '[Trat]_Ko Kut': 'เกาะกูด, ตราด',
    '[Nakhonnayok]_Khao Yai National Park': 'อุทยานแห่งชาติเขาใหญ่, นครนายก ปราจีนบุรี และสระบุรี',
    '[Nakhonnayok]_Khun Dan Prakarn Chon Dam': 'เขื่อนขุนด่านปราการชล, นครนายก',
    '[Chanthaburi]_Homestay': 'ท่องเที่ยวแบบโฮมสเตย์, จันทบุรี',
    '[Srakaeo]_Pang Sida National Park': 'อุทยานแห่งชาติปางสีดา, สระแก้ว',
    '[Prachinburi]_Sri Mahosod Archaeological Site': 'เมืองโบราณศรีมโหสถ, ปราจีนบุรี',
    '[Chanthaburi]_Cathedral of the Immaculate Conception': 'อาสนวิหารพระนางมารีอาปฏิสนธินิรมล, จันทบุรี',
    '[Chanthaburi]_Ko Proet': 'เกาะเปริด, จันทบุรี',
    '[Chanthaburi]_Chao Lao Beach': 'หาดเจ้าหลาว, จันทบุรี',
    '[Prachinburi]_Jakrapong Reservior': 'อ่างเก็บน้ำจักรพงษ์, ปราจีนบุรี'    
}